# this file is used by github marketplace
# it has to be named exactly `action.yml`
name: "rewiser-gpt"
description: "send rewiser email"
author: "Mohit Sharma <mohitlakshya@gmail.com"
inputs:
  to_email:
    description: "The email Id to sent to"
    required: true
  from_email:
    description: "The email Id to send from"
    required: true 
  doc_directory:
    description: "The directory to read files from"
    required: true
  smtp_hostname:
    description: "SMTP Hostname/endpoint"
    required: true
  smtp_port:
    description: "SMTP server port"
    required: true
  smtp_username:
    description: "SMTP server username, used for logging in"
    required: true
  smtp_password:
    description: "SMTP server password, used for logging in"
    required: true
  openai_api_key:
    description: "OpenAI API Key for generating questions"
    required: false

runs:
  using: "composite"
  steps:
    - name: Send Rewiser mail
      run: |
        echo "exporting environment variables"
        export INPUT_TO_EMAIL=${{ inputs.to_email }}
        export INPUT_FROM_EMAIL=${{ inputs.from_email }}
        export INPUT_DOC_DIRECTORY=${{ inputs.doc_directory }}
        export INPUT_SMTP_HOSTNAME=${{ inputs.smtp_hostname }}
        export INPUT_SMTP_PORT=${{ inputs.smtp_port }}
        export INPUT_SMTP_USERNAME=${{ inputs.smtp_username }}
        export INPUT_SMTP_PASSWORD=${{ inputs.smtp_password }}
        export INPUT_OPENAI_API_KEY=${{ inputs.openai_api_key }}
        echo "installing python dependencies"
        pip install -r ${GITHUB_ACTION_PATH}/requirements.txt
        python ${GITHUB_ACTION_PATH}/main.py
      shell: bash

branding:
  icon: 'book-open'
  color: 'blue'
